@url_dev=http://localhost:3055/v1/api/

### create product
POST {{url_dev}}product
Content-Type: application/json
x-api-key:accb6aa0da55a1c7ac5529dee961b14b2923e1329c2705a73e7b032bf7e2b190c246ed6f72e2884ae533c6b1de73492c563263e72c2ea2e17535fbeb988a8ead
x-client-id:64837b6bf0259c87e06b99f0
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDgzN2I2YmYwMjU5Yzg3ZTA2Yjk5ZjAiLCJlbWFpbCI6InNoaXBjbmR2bjAxMTEycTdAZ21haWwuY29tIiwiaWF0IjoxNjg2MzM4ODk3LCJleHAiOjE2ODY1MTE2OTd9.eOldA4V_QQZDvxSIMimga8WOBU0Tf8EyaFYdIYwPY2s
# {
#     "product_name":"name 1",
#     "product_thumb":"htt",
#     "product_description":"hello nam",
#     "product_price": 50,
#     "product_quantity": 5,
#     "product_type":"Clothing",
#     "product_attributes": {
#         "brand":"Leven",
#         "size": "L",
#         "material":"Denin"
#     }
# }

# {
#     "product_name":"IPhone 14 64G",
#     "product_description":"New product",
#     "product_price": 500,
#     "product_type":"Electronic",
#     "product_thumb":"product_thumb",
#     "product_quantity": 5,
#     "product_attributes": {
#         "manufacturer":"Apple",
#         "model": "iPhone 14",
#         "color":"Gold"
#     }
# }

# {
#     "product_name":"Furniture 24",
#     "product_description":"New product",
#     "product_price": 500,
#     "product_type":"Furniture",
#     "product_thumb":"product_thumb",
#     "product_quantity": 5,
#     "product_attributes": {
#         "brand":"TTF",
#         "size": "15",
#         "material":"Gold"
#     }
# }

{
    "product_name":"Băng Quấn Bảo Vệ Khuỷu Tay 2",
    "product_thumb":"http://",
    "product_description":"Áo Thun Nam",
    "product_price": 1234.000,
    "product_quantity": 23,
    "product_type":"Clothing",
    "product_attributes": {
        "brand":"TTF",
        "size": "15",
        "material":"Gold"
    }
}


### action published product
POST {{url_dev}}product/publish/6484c67de64a9fd8e2d74182
Content-Type: application/json
x-api-key:accb6aa0da55a1c7ac5529dee961b14b2923e1329c2705a73e7b032bf7e2b190c246ed6f72e2884ae533c6b1de73492c563263e72c2ea2e17535fbeb988a8ead
x-client-id:64837b6bf0259c87e06b99f0
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDgzN2I2YmYwMjU5Yzg3ZTA2Yjk5ZjAiLCJlbWFpbCI6InNoaXBjbmR2bjAxMTEycTdAZ21haWwuY29tIiwiaWF0IjoxNjg2MzM4ODk3LCJleHAiOjE2ODY1MTE2OTd9.eOldA4V_QQZDvxSIMimga8WOBU0Tf8EyaFYdIYwPY2s

### action unpublished product
POST {{url_dev}}product/unpublish/64837d96b973da2252494609
Content-Type: application/json
x-api-key:accb6aa0da55a1c7ac5529dee961b14b2923e1329c2705a73e7b032bf7e2b190c246ed6f72e2884ae533c6b1de73492c563263e72c2ea2e17535fbeb988a8ead
x-client-id:64837b6bf0259c87e06b99f0
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDgzN2I2YmYwMjU5Yzg3ZTA2Yjk5ZjAiLCJlbWFpbCI6InNoaXBjbmR2bjAxMTEycTdAZ21haWwuY29tIiwiaWF0IjoxNjg2MzM4ODk3LCJleHAiOjE2ODY1MTE2OTd9.eOldA4V_QQZDvxSIMimga8WOBU0Tf8EyaFYdIYwPY2s

### get list Drafts
GET {{url_dev}}product/drafts/all
Content-Type: application/json
x-api-key:accb6aa0da55a1c7ac5529dee961b14b2923e1329c2705a73e7b032bf7e2b190c246ed6f72e2884ae533c6b1de73492c563263e72c2ea2e17535fbeb988a8ead
x-client-id:64837b6bf0259c87e06b99f0
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDgzN2I2YmYwMjU5Yzg3ZTA2Yjk5ZjAiLCJlbWFpbCI6InNoaXBjbmR2bjAxMTEycTdAZ21haWwuY29tIiwiaWF0IjoxNjg2MzM4ODk3LCJleHAiOjE2ODY1MTE2OTd9.eOldA4V_QQZDvxSIMimga8WOBU0Tf8EyaFYdIYwPY2s

### get list Publish
GET {{url_dev}}product/published/all
Content-Type: application/json
x-api-key:accb6aa0da55a1c7ac5529dee961b14b2923e1329c2705a73e7b032bf7e2b190c246ed6f72e2884ae533c6b1de73492c563263e72c2ea2e17535fbeb988a8ead
x-client-id:64837b6bf0259c87e06b99f0
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDgzN2I2YmYwMjU5Yzg3ZTA2Yjk5ZjAiLCJlbWFpbCI6InNoaXBjbmR2bjAxMTEycTdAZ21haWwuY29tIiwiaWF0IjoxNjg2MzM4ODk3LCJleHAiOjE2ODY1MTE2OTd9.eOldA4V_QQZDvxSIMimga8WOBU0Tf8EyaFYdIYwPY2s

### get list search
GET {{url_dev}}product/search/thun
Content-Type: application/json
x-api-key:accb6aa0da55a1c7ac5529dee961b14b2923e1329c2705a73e7b032bf7e2b190c246ed6f72e2884ae533c6b1de73492c563263e72c2ea2e17535fbeb988a8ead
x-client-id:64837b6bf0259c87e06b99f0
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDgzN2I2YmYwMjU5Yzg3ZTA2Yjk5ZjAiLCJlbWFpbCI6InNoaXBjbmR2bjAxMTEycTdAZ21haWwuY29tIiwiaWF0IjoxNjg2MzM4ODk3LCJleHAiOjE2ODY1MTE2OTd9.eOldA4V_QQZDvxSIMimga8WOBU0Tf8EyaFYdIYwPY2s

### get all product
GET {{url_dev}}product/
Content-Type: application/json
x-api-key:accb6aa0da55a1c7ac5529dee961b14b2923e1329c2705a73e7b032bf7e2b190c246ed6f72e2884ae533c6b1de73492c563263e72c2ea2e17535fbeb988a8ead
x-client-id:64837b6bf0259c87e06b99f0
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDgzN2I2YmYwMjU5Yzg3ZTA2Yjk5ZjAiLCJlbWFpbCI6InNoaXBjbmR2bjAxMTEycTdAZ21haWwuY29tIiwiaWF0IjoxNjg2MzM4ODk3LCJleHAiOjE2ODY1MTE2OTd9.eOldA4V_QQZDvxSIMimga8WOBU0Tf8EyaFYdIYwPY2s

### get product by product id
GET {{url_dev}}product/64837d96b973da2252494609
Content-Type: application/json
x-api-key:accb6aa0da55a1c7ac5529dee961b14b2923e1329c2705a73e7b032bf7e2b190c246ed6f72e2884ae533c6b1de73492c563263e72c2ea2e17535fbeb988a8ead
x-client-id:64837b6bf0259c87e06b99f0
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDgzN2I2YmYwMjU5Yzg3ZTA2Yjk5ZjAiLCJlbWFpbCI6InNoaXBjbmR2bjAxMTEycTdAZ21haWwuY29tIiwiaWF0IjoxNjg2MzM4ODk3LCJleHAiOjE2ODY1MTE2OTd9.eOldA4V_QQZDvxSIMimga8WOBU0Tf8EyaFYdIYwPY2s

### get product by product id
PATCH {{url_dev}}product/64837d96b973da2252494609
Content-Type: application/json
x-api-key:accb6aa0da55a1c7ac5529dee961b14b2923e1329c2705a73e7b032bf7e2b190c246ed6f72e2884ae533c6b1de73492c563263e72c2ea2e17535fbeb988a8ead
x-client-id:64837b6bf0259c87e06b99f0
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDgzN2I2YmYwMjU5Yzg3ZTA2Yjk5ZjAiLCJlbWFpbCI6InNoaXBjbmR2bjAxMTEycTdAZ21haWwuY29tIiwiaWF0IjoxNjg2MzM4ODk3LCJleHAiOjE2ODY1MTE2OTd9.eOldA4V_QQZDvxSIMimga8WOBU0Tf8EyaFYdIYwPY2s

{
    "product_name": "Băng Quấn Bảo Vệ Khuỷu Tay 2",
    "product_price": "1234",
    "product_type": "Clothing",
    "product_attributes": {
        "brand": "TTF",
        "size": "15",
        "material": "Gold"
    }
}